### ISSUE TITLE
hfsplus compiled for wrong arch

### ISSUE THREAD

**Issue by smitben59** [itsnebulalol/palera1n#1]
zsh: bad CPU type in executable: ./binaries/Darwin/hfsplus
Nice project btw

**Comment by smitben59** [comment]
I compiled hfsplus for x64 intel and it seems to be functional.

**Comment by itsnebulalol** [comment]
Can you send me that one? So i can test on m1 and add it to the repo

**Comment by smitben59** [comment]
I'm new to GitHub, should I do a fork then add it there?

**Comment by itsnebulalol** [comment]
Just upload it to mega or something then send it here

**Comment by smitben59** [comment]
https://drive.google.com/drive/folders/1Neib8mulPSyL8zHXttQGqZ5RayhJp1Zs?usp=sharing
I also included the other Kernel64Patcher.

**Comment by itsnebulalol** [comment]
I guess i have to build for linux too

**Comment by itsnebulalol** [comment]
Fixed in latest commit
