### ISSUE TITLE
iphone 7 15,4,1 Failed to read shshFile

### ISSUE THREAD

**Issue by rubensalbukrk** [itsnebulalol/palera1n#14]
rubens@rubensdev:~/palera1n$ ./palera1n.sh bub.shsh2 --dfu 15.4.1 --debug
palera1n | Version 1.0.0
Written by Nebula | Some code by Nathan | Patching commands and ramdisk by Mineek | Loader app by Amy

[*] Getting device info...
[*] Pwning device
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0C ECID:000E415818EAED26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[*] Downloading BuildManifest
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022FCSWinter/fullrestores/002-80968/632A8FE7-E1FA-4D3E-BCAC-821DA57D96DA/iPhone_4.7_P3_15.4.1_19E258_Restore.ipsw
init done
getting: BuildManifest.plist
  0%  [==========================================================================100% [===================================================================================================>]
download succeeded
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
img4tool: failed with exception:
[exception]:
what=Failed to read shshFile
code=19529736
line=298
file=main.cpp
commit count=197
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f
[-] An error occurred

what is ?
i try again after run  ./palera1n.sh clean

**Comment by itsnebulalol** [comment]
Your blob is either:
1. invalid
2. doesn’t exist in that path
Double check the location of the blob, and make sure it’s an onboard dumped from SSHRD_Script

**Comment by kristenlc** [comment]
You need to give the entire full path of the shsh file in itsnebulalol script of palera1n for it to be able to read the shsh file. If you use my fork of palera1n https://github.com/kristenlc/palera1n-High-Sierra it will be able to see relative paths.

**Comment by itsnebulalol** [comment]
img4tool is able to read relative paths already

**Comment by kristenlc** [comment]
> img4tool is able to read relative paths already

Yes when executed from the command line directly, but from your script it prints this error. I was able to reproduce this error on my machine also. My repo fixed this by converting command line argument in $1 to a full path and using the full path passed into img4tool as a variable argument.

**Comment by itsnebulalol** [comment]
I can add that upstream

**Comment by kristenlc** [comment]
> I can add that upstream

I would pr, and I really wish to pr things but my entire thing conflicts with yours now because of all the changes. It won't let me pr.

**Comment by itsnebulalol** [comment]
I can see what you changed and manually add them

**Comment by blanxd** [comment]
wow this looks complicated @kristenlc :) why not just use `realpath` - it's present in any posix system, linux just spits stuff in stderr if it cannot resolve it, mac doesn't even try to resolve it so yeah actually need to make sure it's there, I'd do it something like this
```
shsh=$(realpath "${1}" 2>/dev/null)
[ -n "${shsh}" -a -f "${shsh}" ] || {
	echo "[-] cannot read ${1} (${shsh})"
	exit
}
```

**Comment by kristenlc** [comment]
UPDATE: There has been a video tutorial made for checkm8 vulnerable devices to use palera1n if they are running iOS 15.0 to 15.5 beta 4. The tutorial was made for intel mac computers running high sierra. [iOS 15.0 - 15.5b4 JAILBREAK: Sileo ACHIEVED by palera1n Jailbreak - YouTube](https://www.youtube.com/watch?v=fdyHjS1WqKg)
