### ISSUE TITLE
when starting ramdisk it crashes on iPhone 7 plus GSM iOS 15.6

### ISSUE THREAD

**Issue by linhbg1998** [itsnebulalol/palera1n#15]
when starting ramdisk it crashes on iPhone 7 plus GSM iOS 15.6
![IMG_20220920_132801](https://user-images.githubusercontent.com/52190759/191183725-caea197b-52fc-4af4-930d-b5cd3b186ab8.jpg)

**Comment by itsnebulalol** [comment]
As I said, the ramdisk is work in progress and doesn't work as of now.
