### ISSUE TITLE
15.5b1?

### ISSUE THREAD

**Issue by Mabastcity** [itsnebulalol/palera1n#16]
I have trollstore can i run palera1n on 15.5b1 ?

**Comment by kristenlc** [comment]
yes, you can

**Comment by kristenlc** [comment]
UPDATE: There has been a video tutorial made for checkm8 vulnerable devices to use palera1n if they are running iOS 15.0 to 15.5 beta 4. The tutorial was made for intel mac computers running high sierra. [iOS 15.0 - 15.5b4 JAILBREAK: Sileo ACHIEVED by palera1n Jailbreak - YouTube](https://www.youtube.com/watch?v=fdyHjS1WqKg)
