### ISSUE TITLE
d10ap iPhone9,1 downloads DeviceTree for d101ap

### ISSUE THREAD

**Issue by smitben59** [itsnebulalol/palera1n#2]

**Comment by itsnebulalol** [comment]
Can you try the latest commit, this should've been fixed

**Comment by smitben59** [comment]
> Can you try the latest commit, this should've been fixed

Yes I will test shortly!

**Comment by smitben59** [comment]
I'm going to try adapting this project to support downgrades without rootfs sealing as well.

**Comment by itsnebulalol** [comment]
This was fixed awhile ago, forgot to close
