### ISSUE TITLE
Bundled kernel64patcher doesn't have root hash patch "-o"

### ISSUE THREAD

**Issue by smitben59** [itsnebulalol/palera1n#3]
iSuns9 Kernel64Patcher has it but the one bundled has no '-o' option

**Comment by itsnebulalol** [comment]
Wouldn’t that break the seal?

**Comment by smitben59** [comment]
The device can't boot without auth blob/ root hash being patched on iOS 15, it's in the iOS 15 kernel cache

**Comment by itsnebulalol** [comment]
Never mind I misread

**Comment by itsnebulalol** [comment]
Yeah, that should be the issue. Need to compile the fork

**Comment by smitben59** [comment]
Only issue is Kerneldiff doesn't work properly after -o option is passed.

**Comment by itsnebulalol** [comment]
Fixed in latest commit
