### ISSUE TITLE
An error occurred on iphone7 ios15.5beta4

### ISSUE THREAD

**Issue by xiuxianchengdi** [itsnebulalol/palera1n#8]
[*] Getting device info...
[*] Pwning device
[*] Downloading BuildManifest
[-] An error occurred

**Comment by itsnebulalol** [comment]
Is your blob valid? If you run `git pull` then add `--debug` to the end of the command, and send the full log I can help. Also, please send the command you ran.

**Comment by xiuxianchengdi** [comment]
there is an other issue
./palera1n.sh /Users/admin/palera1n/blob.shsh2 --debug
palera1n | Version 1.0.0
Written by Nebula | Some code by Nathan | Patching commands and ramdisk by Mineek | Loader app by Amy

Hello, iPhone9,1 on 15.5!
[*] Switching device into recovery mode...
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
[*] Downloading BuildManifest
[*] Downloading and decrypting iBSS
[*] Downloading and decrypting iBEC
[*] Downloading DeviceTree
[*] Downloading trustcache
[*] Downloading kernelcache
[*] Patching and repacking iBSS/iBEC
[*] Patching and converting kernelcache
[*] Converting DeviceTree
[*] Patching and converting trustcache
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[===                                               ] 4.9%
Done!
The device should now boot to iOS
If you already have installed Pogo, click uicache and remount preboot in the tools section
If not, get an IPA from the latest action build of Pogo and install with TrollStore
Add the repo mineek.github.io/repo for Procursus

**Comment by itsnebulalol** [comment]
Please run `./palera1n clean` then run the original command again with '--debug`.

Is that blob in that location valid?

**Comment by xiuxianchengdi** [comment]
I'm sure blob is valid
./palera1n.sh /Users/admin/Desktop/15b4.shsh2  --debug
palera1n | Version 1.0.0
Written by Nebula | Some code by Nathan | Patching commands and ramdisk by Mineek | Loader app by Amy

Hello, iPhone9,1 on 15.5!
[*] Switching device into recovery mode...
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
[*] Downloading BuildManifest
[*] Downloading and decrypting iBSS
[*] Downloading and decrypting iBEC
[*] Downloading DeviceTree
[*] Downloading trustcache
[*] Downloading kernelcache
[*] Patching and repacking iBSS/iBEC
[*] Patching and converting kernelcache
[*] Converting DeviceTree
[*] Patching and converting trustcache
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[===                                               ] 4.9%
Done!
The device should now boot to iOS
If you already have installed Pogo, click uicache and remount preboot in the tools section
If not, get an IPA from the latest action build of Pogo and install with TrollStore
Add the repo mineek.github.io/repo for Procursus

**Comment by itsnebulalol** [comment]
Please run `git pull`, `./palera1n.sh clean`, then run that command again

**Comment by xiuxianchengdi** [comment]
ok, it's boot, but it stay on verbose boot,
bool applem2scalercschal:: ititscal

[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%

Done!

**Comment by itsnebulalol** [comment]
Did it show the whole debug log in the terminal?

**Comment by xiuxianchengdi** [comment]
yes, 
[Terminal Saved Output.log](https://github.com/itsnebulalol/palera1n/files/9598978/Terminal.Saved.Output.log)

**Comment by itsnebulalol** [comment]
Since this is 15.5b4, and ipsw.me’s api doesn’t return betas, can you please grab a 15.5b4 ipsw for your device? Then, open the script in a text editor, and change the ipswurl line to be `ipswurl=link to your ipsw`.

**Comment by xiuxianchengdi** [comment]
is correct?
ipswurl=https://updates.cdn-apple.com/2022SpringSeed/fullrestores/002-94731/C88B0D92-E914-434D-9B9F-A62FFC2B9359/iPhone_4.7_P3_15.5_19F5070b_Restore.ipsw

**Comment by xiuxianchengdi** [comment]
black screen after verbose boot.

**Comment by itsnebulalol** [comment]
> is correct? ipswurl=https://updates.cdn-apple.com/2022SpringSeed/fullrestores/002-94731/C88B0D92-E914-434D-9B9F-A62FFC2B9359/iPhone_4.7_P3_15.5_19F5070b_Restore.ipsw

yes, as long as that's a 15.5b4 ipsw

**Comment by itsnebulalol** [comment]
> black screen after verbose boot.

is your blob valid?

**Comment by xiuxianchengdi** [comment]
yes，I downgraded my device with this blob a few days ago

**Comment by itsnebulalol** [comment]
Can you please try with an onboard blob dumped from SSHRD_Script?

**Comment by xiuxianchengdi** [comment]
How to do that?

**Comment by itsnebulalol** [comment]
Do the steps, but instead of running the ssh command, run `./sshrd.sh dump-blobs`. Then use that blob in palera1n. If you can’t figure it out, this will be implemented automatically soon.

**Comment by xiuxianchengdi** [comment]
apple@localhost SSHRD_Script % ./sshrd.sh dump-blobs
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:000E656820D20F26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:000E656820D20F26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33]
Found the USB handle.
Stage: SPRAY
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:000E656820D20F26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:000E656820D20F26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:000E656820D20F26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: dump-blobs
Error init failed
failed

**Comment by kristenlc** [comment]
UPDATE: There has been a video tutorial made for checkm8 vulnerable devices to use palera1n if they are running iOS 15.0 to 15.5 beta 4. The tutorial was made for intel mac computers running high sierra. [iOS 15.0 - 15.5b4 JAILBREAK: Sileo ACHIEVED by palera1n Jailbreak - YouTube](https://www.youtube.com/watch?v=fdyHjS1WqKg)

**Comment by xiuxianchengdi** [comment]
apple@bogon SSHRD_Script % ./dump_onboard_blobs.sh 15.5b4
[*] Removed the current created SSH ramdisk
[*] Getting device info... this may take a second
dyld: Library not loaded: /usr/local/lib/libimg4tool.0.dylib
  Referenced from: /Users/apple/palera1n-High-Sierra/SSHRD_Script/Darwin/img4tool
  Reason: image not found
./sshrd.sh: line 158:  5497 Abort trap: 6           "$oscheck"/img4tool -e -s shsh/"${check}".shsh -m work/IM4M
[-] An error occurred

**Comment by itsnebulalol** [comment]
Are you on high sierra, if so, follow the commands on the readme.

If not, use the normal version

**Comment by xiuxianchengdi** [comment]
apple@bogon SSHRD_Script % ./sshrd.sh 15.5b4
[*] Waiting for device in DFU mode
[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: null
Error init failed
[-] An error occurred

**Comment by itsnebulalol** [comment]
Use 14.8 for the ramdisk version. Yes, I know you’re on 15.5b4. It doesn’t matter

**Comment by xiuxianchengdi** [comment]
Successful install sileo. Thanks.

**Comment by kristenlc** [comment]
> apple@bogon SSHRD_Script % ./dump_onboard_blobs.sh 15.5b4 [_] Removed the current created SSH ramdisk [_] Getting device info... this may take a second dyld: Library not loaded: /usr/local/lib/libimg4tool.0.dylib Referenced from: /Users/apple/palera1n-High-Sierra/SSHRD_Script/Darwin/img4tool Reason: image not found ./sshrd.sh: line 158: 5497 Abort trap: 6 "$oscheck"/img4tool -e -s shsh/"${check}".shsh -m work/IM4M [-] An error occurred

Thank you for mentioning this, I would have not found out otherwise.
img4tool 190 i think has to be compiled from source also not just libgeneral, otherwise it will err.
I have since updated the [readme](https://github.com/kristenlc/palera1n-High-Sierra/blob/main/README.md) file to reflect this.
My fork is for those who are running high sierra only, and the instructions require more steps for high sierra.
It is recommended to use nebula palera1n if you are running mac os catalina or later.

**Comment by kristenlc** [comment]
> apple@bogon SSHRD_Script % ./dump_onboard_blobs.sh 15.5b4 [_] Removed the current created SSH ramdisk [_] Getting device info... this may take a second dyld: Library not loaded: /usr/local/lib/libimg4tool.0.dylib Referenced from: /Users/apple/palera1n-High-Sierra/SSHRD_Script/Darwin/img4tool Reason: image not found ./sshrd.sh: line 158: 5497 Abort trap: 6 "$oscheck"/img4tool -e -s shsh/"${check}".shsh -m work/IM4M [-] An error occurred

This very specific error has been fixed now! Thank you for letting me know about this error, it should not happen again on the latest version

**Comment by xiuxianchengdi** [comment]
yes，I downgraded my device with this blob a few days ago
