### ISSUE TITLE
error when booting in iPhone 7 plus GSM (iPhone 9.4 iOS 15.3.1)

### ISSUE THREAD

**Issue by linhbg1998** [itsnebulalol/palera1n#9]
after i boot the device loads ibss and the device reboots.  i use other methods the device does not restore to recovery mode but to dfu

**Comment by itsnebulalol** [comment]
Are you using usb-c? Are you on linux or macOS? Did you enter DFU right from recovery?

**Comment by blanxd** [comment]
and mentioning just in case, even if using a USB hub, it doesn't seem to run on M1 (ie. gaster doesn't do its job, I tried all sorts of forks, built them for arm and intel, no success on M1).

**Comment by itsnebulalol** [comment]
The gaster fork it uses works perfectly fine on my M1 Mac with a usb hub (as you need usb-a).

**Comment by blanxd** [comment]
wow, ok tnx for replying. This is good to know, maybe I've hacked something else too far then or a bad hub or will try another port for it etc. Tnx!

**Comment by blanxd** [comment]
@itsnebulalol I was using an intel one on Catalina no prob, but now I found it must have been the macOS, I was on 12.4, now upgraded to 12.6 and it works fine on M1, indeed.
